[[MUSCLE]]
arch = "aarch64"
git-tree-sha1 = "e2006ead2cb9f5c9049546f1ebc834cbf544d88d"
os = "macos"

    [[MUSCLE.download]]
    sha256 = "b224c3d2cabc29f55546d53f6687a414c8c19f5666ae8c9d90b445de27fd830d"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.aarch64-apple-darwin.tar.gz"
[[MUSCLE]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e59c1a82bce05842585bd8e1f46c68e30f155504"
libc = "glibc"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "4aa53190ae6a149a0fe58956b2a35c9bb5bcd5500a974c743a8624f56f84e6ac"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[MUSCLE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e1de0d995646d19430fab506f0d29f4d02ab1f6"
libc = "glibc"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "e0bf5eca47e75bcbbde2226f6bd61d8c3c50d5ecbddc01db62397d610bd89f6a"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MUSCLE]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db038a13d3c66934ec166c275127444bf52244fa"
libc = "musl"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "c9397ac8514a191895c29adaed14ba705157be9079a0a8ff3bba32665f86a63f"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[MUSCLE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f32cb8c9df22cbfd5c302bd07981182deccdc174"
libc = "musl"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "3b61a045b3e251a58e282fd1013dd2a7a7a6bacb965ee059f89bec6e5e5c1997"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[MUSCLE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1d2a2a58a1eed08ebf853c4107bee5652a6c8ed"
libc = "glibc"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "6f9f40d3930d417c35c85056bb54ad0c5420ae4a37c9e51824405cbafb5b58d5"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MUSCLE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a43832cd3796a322acf7f4cb68accc5f0c46f36f"
libc = "glibc"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "73c8307b851bbf34b3f1db3e2f6e6b27d7d6b2bb20dfb3ddbd2d3ef653715d47"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MUSCLE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d40bae5bc052b0d42dd2ff54c64ef9286c38241"
libc = "musl"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "51a2a925114d9f11c73345ca3e35165e04b4b727e9eb86ea01f6710fb1be2890"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MUSCLE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98582584906b235b9430a323ff9569919382596d"
libc = "musl"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "16eae76c8dc1e597227be87ba4de63a52f264583e56830544db1ee00fd61bef3"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MUSCLE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "197bd85b156fb0cbbaac9cbe9d5d121b60e6519a"
libc = "glibc"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "e96e0830b84ccdb1ce2c793f2803c89937107934de7b415c305da8dfbdd0a913"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MUSCLE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af9d775b2f49fd61781e6f1081a4aeadef2cc93e"
libc = "glibc"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "713f75f48d8b9bbfcbdaf0f35affd8f8251416ce55987b396964dca89ce2460e"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MUSCLE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "458c2dfae2e2e43253cbcc3d7bca4bbd3c40b497"
libc = "musl"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "29ca54055cd6a470371b65799a9b88c94c75632ecceb1b408bcbd7652b56c42e"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MUSCLE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "671d4d9ca94201aab8283060520c4bbbf6e8a382"
libc = "musl"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "60b2a1f6695671c9c8b146459cee5b3c963d8341543ee9ab7be98f58ff1e7778"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MUSCLE]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff51d0eb99352dcceb88abc731478dd6ed0f2eef"
libc = "glibc"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "c6cbe7844fd66a06568d7638cf69bdab02909c494cc2b094a323aa78634e3569"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.i686-linux-gnu-cxx03.tar.gz"
[[MUSCLE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e332950228c29fccea8652cdeedc5dc2e06d9b98"
libc = "glibc"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "c5055cfcd99ae1f439973e758e673aea6058f9e9b846e7affac398fbfc14edf3"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.i686-linux-gnu-cxx11.tar.gz"
[[MUSCLE]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3789e0cdd126258caa9a2c38488544475c7d91a4"
libc = "musl"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "e1409f575233531875804c39c7b07c71f8ad4ccdfc1e31e90a3be7c311a52104"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.i686-linux-musl-cxx03.tar.gz"
[[MUSCLE]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82f5128665e3f20ca051d1af786885c363cc5182"
libc = "musl"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "fb23494556680e3fc087fb7b227c918615cd68b0960bdfe183185a6a989a08c4"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.i686-linux-musl-cxx11.tar.gz"
[[MUSCLE]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad3e9720fb36ed1ab621318fa0d897207d26905b"
libc = "glibc"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "efd4eab688ac478bcca682ea12ef92fb547c7a63f236aa7eecd5b7fce8875246"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MUSCLE]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7e47ca2ca7fc4d141982d5b55055728e80236fd"
libc = "glibc"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "430c267e509e9ace311184773b09bd303fb6ef6bf0b7605395cecaa890c92e5e"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MUSCLE]]
arch = "x86_64"
git-tree-sha1 = "cd36354e3ee12d594eb08b697c3621709705e356"
os = "macos"

    [[MUSCLE.download]]
    sha256 = "d09a10d266913b99a29d63c1a47bd05ab21f735575f9606ba87cf1c90dffa0fb"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.x86_64-apple-darwin.tar.gz"
[[MUSCLE]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94df9f83a831bb420804526521e178a1e298f48b"
libc = "glibc"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "9314c1f307c88f01496992464af6f48d8e01654a0689bc8bde16bbd04dcdd289"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[MUSCLE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d82a3891cb60741434fb2d0bf23737c7ed99cfcb"
libc = "glibc"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "8ce6077d679205fd206face84cd3830ab5a7cea4d3412e0527e57c9f9dded67c"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MUSCLE]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c622edd4882fdeaabba912ff5191d9e633411a1"
libc = "musl"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "50961be029b51e046c7caec2e08e10f39025018625eb191f941c5ee1124149a9"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[MUSCLE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86a49edc78dc2f31011af8555b6ea7f16d0dfbd4"
libc = "musl"
os = "linux"

    [[MUSCLE.download]]
    sha256 = "a140468480880cc30c5f04182196f139f44d6760ffc862944cff35123a6763ca"
    url = "https://github.com/JuliaBinaryWrappers/MUSCLE_jll.jl/releases/download/MUSCLE-v5.2.0+1/MUSCLE.v5.2.0.x86_64-linux-musl-cxx11.tar.gz"
