# Autogenerated wrapper script for MUSCLE_jll for aarch64-apple-darwin
export muscle

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("MUSCLE")
JLLWrappers.@declare_executable_product(muscle)
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_executable_product(
        muscle,
        "bin/muscle",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
